production:
  ggle_user: "gconsal"
  ggle_mail: "gconsal@gmail.com"
  ggle_pass: "sasasa"
  db_user: "root"
  db_pass: "lapasswordmaslarga"
  herokuapp: "NO" # Para saber si estoy en Heroku o no. Por el manejo de imágenes.
  SECRET_KEY_BASE: "c38b0d293e53a7c24217cae6f9bc5a19da1895b4028ee91773748c2665dc5d5760d15f13260d325905336525cf23fda49cc585c95e76e96c8189eb793627821d"
  txa_server: "texhaarg.com"
  txa_address: "mail.texhaarg.com"
  #txa_port: "587"
  txa_domain: "texhaarg.com"
  txa_mail: "gconsal@texhaarg.com"
  txa_pass: "Pipoto25"
  txa_authentication: "login"
  txa_enable_starttls_auto: "true"
  txa_openssl_verify_mode: "none"

development:
  ggle_user: "gconsal"
  ggle_mail: "gconsal@gmail.com"
  ggle_pass: "sasasa"
  db_user: "root"
  db_pass: "lapasswordmaslarga"
  txa_mail: "gconsal@texhaarg.com"
  txa_pass: "Pipoto25"
  herokuapp: "NO" # Para saber si estoy en Heroku o no. Por el manejo de imágenes.
  SECRET_KEY_BASE: "c38b0d293e53a7c24217cae6f9bc5a19da1895b4028ee91773748c2665dc5d5760d15f13260d325905336525cf23fda49cc585c95e76e96c8189eb793627821d"
  txa_server: "localhost:3000"
  txa_address: "mail.texhaarg.com"
  #txa_port: "587"
  txa_domain: "texhaarg.com"
  txa_mail: "gconsal@texhaarg.com"
  txa_pass: "Pipoto25"
  txa_authentication: "login"
  txa_enable_starttls_auto: "true"
  txa_openssl_verify_mode: "none"
